apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  pull_request:
    branches:
      - 'main'

jobs:
 
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"